# Generated by Django 3.1.6 on 2021-02-05 21:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='код элемента')),
                ('value', models.CharField(max_length=255, verbose_name='значение элемента')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
            },
        ),
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='наименование')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='короткое наименование')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('version', models.CharField(max_length=15, verbose_name='Версия справочника')),
                ('begin_at', models.DateField(default=datetime.date(2021, 2, 5), verbose_name='Дата начала действия справочника этой версии')),
            ],
            options={
                'verbose_name': 'Справочник',
            },
        ),
        migrations.AddConstraint(
            model_name='referencebook',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_version_of_book'),
        ),
        migrations.AddField(
            model_name='article',
            name='reference_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.referencebook', verbose_name='справочник'),
        ),
    ]
