# Generated by Django 3.1.6 on 2021-02-08 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Элемент справочника', 'verbose_name_plural': 'Элементы справочника'},
        ),
        migrations.AlterModelOptions(
            name='referencebook',
            options={'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterField(
            model_name='article',
            name='reference_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='reference_books.referencebook', verbose_name='справочник'),
        ),
        migrations.AlterField(
            model_name='referencebook',
            name='begin_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала действия справочника этой версии'),
        ),
    ]
